services:

  postgres:
    image: postgres:16
    container_name: taskman_postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - taskman_pgdata:/var/lib/postgresql/data

  app:
    image: taskman
    container_name: taskman_app
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/taskdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  taskman_pgdata: